# mkdocs.yml
site_name: UMLBot
site_url: https://sites.uab.edu/periop-datascience/
repo_url: https://github.com/uabperiopai
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Tests: tests/README.md
  - 'UMLBot':
    - Package Init: 'UMLBot/__init__.md'
    - API Server: 'UMLBot/api_server.md'
    - Exceptions: 'UMLBot/exceptions.md'
    - LLM Interface: 'UMLBot/llm_interface.md'
    - UML Draft Handler: 'UMLBot/uml_draft_handler.md'
    - Services:
      - Init: 'UMLBot/services/__init__.md'
      - Diagram Service: 'UMLBot/services/diagram_service.md'
    - Utils:
      - PlantUML Extractor: 'UMLBot/utils/plantuml_extractor.md'
    - Config:
      - Init: 'UMLBot/config/__init__.md'
      - Config: 'UMLBot/config/config.md'
    - User Interface: 'UMLBot_streamlit_app.md'

  - llm_utils: '!include ./llm_utils/mkdocs.yml'

theme:
  name: readthedocs
plugins:
  - search
  - monorepo
  - mkdocstrings:
      handlers:
        python:
          paths: ['UMLBot', 'llm_utils']  # search packages in these folders
watch:
  - .  # reload docs for any file changes
use_directory_urls: false
