version: "3.8"

services:
  umlbot-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        PROJECT_NAME: UMLBot
        PYTHON: "3.11"
        USERNAME: vscode
        NODE_VERSION: "18"
    volumes:
      - ..:/workspaces/UMLBot:cached
      - umlbot-venv:/workspaces/UMLBot/.venv
      - umlbot-frontend-node_modules:/workspaces/UMLBot/app/frontend/node_modules
    command: sleep infinity

  plantuml:
    image: plantuml/plantuml-server:latest
    container_name: umlbot-plantuml
    restart: unless-stopped

volumes:
  umlbot-venv:
  umlbot-frontend-node_modules:
